input {
  tcp {
    port => 4560
    codec => json_lines
  }
  tcp {
    port => 4561
    codec => json_lines
  }
  tcp {
    port => 4562
    codec => json_lines
  }
  tcp {
    port => 4563
    codec => json_lines
  }
}

output {
  elasticsearch {
    hosts => ["http://es:9200"]
    index => "mall-logs-%{+YYYY.MM.dd}"
  }
  stdout {
    codec => rubydebug
  }
}