version: '3'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3307:3306
    volumes:
      - ./mydata/mysql/data/db:/var/lib/mysql
      - ./mydata/mysql/data/conf:/etc/mysql/conf.d
      - ./mydata/mysql/log:/var/log/mysql
  redis:
    image: redis:7
    container_name: redis
    command: redis-server --appendonly yes
    volumes:
      - ./mydata/redis/data:/data
      - ./mydata/redis/log:/var/log/redis
    ports:
      - 6379:6379
  nginx:
    image: nginx:1.22
    container_name: nginx
    volumes:
      - ./mydata/nginx/log:/var/log/nginx
    ports:
      - 81:80
  rabbitmq:
    image: rabbitmq:3.9.11-management
    container_name: rabbitmq
    volumes:
      - ./mydata/rabbitmq/data:/var/lib/rabbitmq
      - ./mydata/rabbitmq/log:/var/log/rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
  elasticsearch:
    image: elasticsearch:7.17.3
    container_name: elasticsearch
    user: root
    environment:
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
      - "cluster.name=elasticsearch"
      - "discovery.type=single-node"
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    volumes:
      - ./mydata/elasticsearch/plugins:/usr/share/elasticsearch/plugins
      - ./mydata/elasticsearch/data:/usr/share/elasticsearch/data
      - ./mydata/elasticsearch/log:/usr/share/elasticsearch/logs
    ports:
      - 9200:9200
      - 9300:9300
  logstash:
    image: logstash:7.17.3
    container_name: logstash
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./mydata/logstash/log:/usr/share/logstash/logs
    depends_on:
      - elasticsearch
      - elasticsearch
    links:
      - elasticsearch:es
      - elasticsearch:es
    ports:
      - 4560:4560
      - 4561:4561
      - 4562:4562
      - 4563:4563
  kibana:
    image: kibana:7.17.3
    container_name: kibana
    volumes:
      - ./mydata/kibana/log:/usr/share/kibana/logs
    links:
      - elasticsearch:es
      - elasticsearch:es
    depends_on:
      - elasticsearch
      - elasticsearch
    environment:
      - "elasticsearch.hosts=http://es:9200"
      - "elasticsearch.hosts=http://es:9200"
    ports:
      - 5601:5601
  mongo:
    image: mongo:4
    container_name: mongo
    volumes:
      - ./mydata/mongo/db:/data/db
      - ./mydata/mongo/log:/var/log/mongodb
    ports:
      - 27017:27017
  nacos-registry:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos-registry
    environment:
      - "MODE=standalone"
    volumes:
      - ./mydata/nacos/log:/home/nacos/logs
    ports:
      - 8848:8848